### PR TITLE
Fixed accessibility related issues on student admin tab

### PR DESCRIPTION
**Pull request by amir-qayyum-khan**
Hi

Working for MIT ODL. In this PR I fixed accessibility related issues on student admin tab inside CCX dashboard.

Now screen readers can read student admin tab i.e can read grade book and download it. You can use screen reading tools like chromeVox (A chrome browser plugin) or command + F5 on mac to verify this PR.
Also read http://edx-partner-course-staff.readthedocs.org/en/latest/getting_started/accessibility.html

EDX https://github.com/edx/edx-platform/pull/7897
@carsongee @pdpinch @pwilkins

### CODE REVIEW

**Comment by bdero** [comment]
@amir-qayyum-arbisoft Could you rebase this PR and point it to master? It looks like the branch is either too far ahead of mitx-inator-20150512 or github improperly rendered the diff.

**Comment by amir-qayyum-arbisoft** [comment]
@bdero done with rebase

CC @pdpinch

**Comment by carsongee** [comment]
This looks good to me.  Are we planning on merging all these PRs into one for edX?  It will probably be easier that way.

**Comment by amir-qayyum-khan** [comment]
@carsongee after you guys give me go ahead on this I will open this PR on edX platform. We will merge it there. Thanks

cc @pdpinch

**Comment by pdpinch** [comment]
Thanks guys. We are waiting first on an accessibility review by Mark Sadecki at edX before moving forward on this. 

----------------
I am mobile.

**Comment by amir-qayyum-khan** [comment]
ok sure

**Comment by pwilkins** [comment]
Closed because it doesn't address issues identified by Mark Sadecki in his accessibility audit.

**Pull request closed without merging**
