### PR TITLE
Added explicit labels on Enrollment tab inside CCX dashboard to fix #21

### LINKED ISSUE #21: CCX: Accessibility - add explicit labels
Explicit labels are<label> elements that programmatically associate form fields with accessible text. Many of the fields missing accessible labels in CCX have visible text labels already. They just need to be wrapped in<label> elements. <label> elements can be associated with input fields in one of two ways; an implied relationship is assumed if the input is a child of the<label>, explicit relationships can be defined using a for attribute on the<label> element that references an id attribute on the input.

# Instructor Dashboard
## Course Team Management
- The “Enter username or email” form field is missing an explicit label [1].
# CCX Coach Dashboard
### Batch Enrollment
- “Email Addresses/Usernames” textarea is missing an explicit label.
- “Auto Enroll” checkbox is missing an explicit label.
- “Notify users by email” checkbox is missing an explicit label.

## Student List Management
- “Enter username or email” form field is missing an explicit label.

### Schedule a Unit

- “Section” select menu is missing an explicit label.
- “Subsection” select menu is missing an explicit label.
- “Unit” select menu is missing an explicit label.
- “Start Date” is missing explicit label
- “Start Time” is missing explicit label
- “Due Date” is missing explicit label
- “Due Time” is missing explicit label

(copied verbatim from Mark Sadecki's CCX Accessibility audit - July 17, 2015)

### PR DESCRIPTION
**Pull request by amir-qayyum-khan**
HI,

### Issue
(copied verbatim from Mark Sadecki's CCX Accessibility audit - July 17, 2015)

"Explicit labels are elements that programmatically associate form fields with accessible text. Many of the fields missing accessible labels in CCX have visible text labels already. They just need to be wrapped in elements. elements can be associated with input fields in one of two ways; an implied relationship is assumed if the input is a child of the, explicit relationships can be defined using a for attribute on the element that references an id attribute on the input.

#### Enrollment Tab
- “Email Addresses/Usernames” textarea is missing an explicit label.
- “Auto Enroll” checkbox is missing an explicit label.
- “Notify users by email” checkbox is missing an explicit label.

#### Address In this PR
In this PR I fixed explicit labels related issues on enrollment tab inside ccx coach dashboard.

Now screen readers can read  administration list management section and can invite CCX coach . You can use screen reading tools like chromeVox (A chrome browser plugin) or command + F5 on mac to verify this PR.
Also read http://edx-partner-course-staff.readthedocs.org/en/latest/getting_started/accessibility.html

EDX https://github.com/edx/edx-platform/pull/7921
https://github.com/mitocw/edx-platform/issues/21

@pdpinch @pwilkins

### CODE REVIEW

**Comment by pdpinch** [comment]
@pwilkins can you edit the cover letter to invoke Mark Sadecki's name & instructions? 

We'll use the same cover letter when we submit to edX. 

- Peter

**Comment by pwilkins** [comment]
@pdpinch I will update the cover letter as you suggest.

**Comment by amir-qayyum-khan** [comment]
@pwilkins this PR only address issues related to Enrollment tab in ccx coach dashboard.

cc @pdpinch

**Comment by pdpinch** [comment]
@amir-qayyum-khan @pwilkins can one of you edit the title and the description of the PR to better match what it contains?

**Comment by amir-qayyum-khan** [comment]
let me @pdpinch

**Comment by amir-qayyum-khan** [comment]
Fixed in https://github.com/edx/edx-platform/pull/9038

**Pull request closed without merging**
