### PR TITLE
Fixed authentication classes to support Django OAUTH Toolkit

### PR DESCRIPTION
**Pull request by amir-qayyum-khan**
### Background
Fixes https://github.com/mitocw/edx-platform/issues/244

### What is done in this PR
**Studio Updates:** None.
**LMS Updates:** 
- Fixes the authentication and authorization classes for the ccx REST APIs

### How to test:
Try to access ``http://localhost:8000/api/ccx/v0/ccx/?master_course_id=<master course id>`` via Django OAUTH Toolkit Access token.

@pdpinch @giocalitri

### CODE REVIEW

**Comment by amir-qayyum-khan** [comment]
@pdpinch it is fix and need to move to upstream so that it can be merge into edX https://github.com/mitocw/edx-platform/pull/256

**Comment by giocalitri** [comment]
I think the code is fine overall, but I have 2 big comments:

1- the tests should not be modifies, the old ones are fine as they are. You just need to add more to test that ALSO the Django OAUTH toolkit works. The new permission classes support both OAUTH apps, so the tests need to test both.
2- I do not think that the permission classes you used are fine: they also allow Inactive users to access the endpoints. This is fine for other endpoints, but I am not sure that in this case we need to let this kind of users to access the CCX endpoint. (But I leave the decision to @pdpinch )

**Comment by amir-qayyum-khan** [comment]
@giocalitri 

> 1- the tests should not be modified, the old ones are fine as they are. You just need to add more to test that ALSO the Django OAUTH toolkit works. The new permission classes support both OAUTH apps, so the tests need to test both.

**fixed.**

> 2- I do not think that the permission classes you used are fine: they also allow Inactive users to access the endpoints. This is fine for other endpoints, but I am not sure that in this case we need to let this kind of users to access the CCX endpoint. (But I leave the decision to @pdpinch )
 
@pdpinch any suggestions?

**Comment by giocalitri** [comment]
I think the code is fine, but you might have done even too much.
It was probably enough to test fewer cases, but I guess this is complete.

If @pdpinch is fine with the current authentication classes, this is probably good to go.

**Comment by pdpinch** [comment]
@giocalitri and I discussed on hipchat. @amir-qayyum-khan please go ahead and open this upstream.

**Comment by amir-qayyum-khan** [comment]
ok

**Comment by amir-qayyum-khan** [comment]
made upstream https://github.com/edx/edx-platform/pull/13161

**Pull request closed without merging**
