### PR TITLE
Fourth Hotfix Release - Cypress

### LINKED ISSUE #204: RP release of hotfix six
Fixes:

- [x] mathjax rendering bug (TNL-4080) but not all of  [ZenDesk 2995](https://odl.zendesk.com/agent/tickets/2995)
- [x] 2 PRs for Jolyon
- [x] if we're lucky, it will fix [ZenDesk 2503]https://odl.zendesk.com/agent/tickets/2503)

### PR DESCRIPTION
**Pull request by bdero**
address mathjax rendering bug (TNL-4080)
(cherry picked from commit ae279569db184944434e3bfc11a84f392305dfb2)

So far, this release is just a cherry-pick of the mathjax problem + some configuration changes. Let me know if there are other fixes I should append.

CC @blarghmatey @itsbenweeks @pdpinch

fixes #204

### CODE REVIEW

**Comment by blarghmatey** [comment]
:+1:

**Comment by itsbenweeks** [comment]
I'm not sure if MathJax's issues are entirely fixed yet. See https://github.com/edx/edx-platform/pull/11507.

**Comment by bdero** [comment]
Yeah, the cherry-pick I did was just Adam's hack to fix the bar issue I believe. He removes it in the PR you listed in favor of upgrading mathjax (although there might be more problems with mathjax I'm not remembering): https://github.com/edx/edx-platform/pull/11507/files#diff-c7047cb9d48f2f7570fe4f80d519a9fcL476

If there aren't other changes I should cherry-pick into the pipeline for this hotfix, it might be worth waiting at least until the mathjax upgrade PR is merged. Thoughts @itsbenweeks & @pdpinch ?

**Comment by itsbenweeks** [comment]
I'm all for waiting until both the dot and the bar issues are resolved.

**Comment by pdpinch** [comment]
We've also got Jolyon's PRs, and I can't remember if the save button race condition bugfix was already cherry picked? 

I'll try to dig up the Commit hashes for you.

**Comment by bdero** [comment]
I don't believe we've included the commits to fix the race condition: https://github.com/mitocw/edx-platform/commits/c1e3306ac5b77b863d51be906a027925e7588afd

What's the PR on edX for that again?

Thanks for linking Jolyon's changes here: https://odl.zendesk.com/agent/tickets/3044

**Comment by pdpinch** [comment]
Here's the race condition bug fix: https://github.com/edx/edx-platform/pull/10617 
c6abe16d5e26b593732f79af55b6e51b1d7078e7

**Comment by pdpinch** [comment]
Does not fix #191

Fixes some future issue to be named.

**Comment by bdero** [comment]
Ok, I've cherry-picked the race condition fix and Jolyon's two commits. Is there anything else we should add to this release?

**Comment by pdpinch** [comment]
Gradebook fixes are not ready yet. This is everything. 

I do want to review all 3 of these before we go to production. Will you deploy to the -staging stack? 

----------------
I am mobile.

**Comment by bdero** [comment]
Yes, these will go to staging to be tested first.

**Comment by bdero** [comment]
@pdpinch Should we should plan to deploy this stuff on Staging Tuesday morning so that we can deploy RP on the same day after testing if all is well?

**Comment by pdpinch** [comment]
Let's shoot for Tuesday -- that in of itself may be hard with planning.

**Comment by bdero** [comment]
This is deployed to staging and ready for review.

**Comment by itsbenweeks** [comment]
Unfortunately, the MathJax issue persists:
image

**Comment by pdpinch** [comment]
Ok, the race condition seems to work. I'm not sure if it's really going to make a difference, but it does prevent hitting the check button while a save is performing. 

I tested with one of Ike's mega-questions at https://lms-staging.mitx.mit.edu/courses/MITx/8.371/2016_Spring/courseware/week2/Fun_with_stabilizers/

**Comment by pdpinch** [comment]
:+1:

**Pull request merged**
