### PR TITLE
MITx cypress hotfix.1 rc

### PR DESCRIPTION
**Pull request by carsongee**
@bdero, we may want to wait until they seal Cypress, but I'm above average confident that this will be all there is.

### CODE REVIEW

**Comment by carsongee** [comment]
Can I get a quick review and thumbs that this is the same as the final cypress release? @bdero or @pdpinch ?

**Comment by bdero** [comment]
Looks good to me :zap:

**Comment by carsongee** [comment]
Thanks

**Comment by carsongee** [comment]
Just a note, the branch is wrong here, and I pushed this branch to the correct name: mitx-cypress.1-hotfix.1

**Pull request merged**
